app:
  jwtExpirationInMs: 604800000
  jwtSecret: JWTSuperSecretKeyHelloWorldJWTSuperSecretKeyHelloWorldJWTSuperSecretKeyHelloWorldJWTSuperSecretKeyHelloWorldJWTSuperSecretKeyHelloWorld


spring:
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://localhost:3306/wiwy?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root1234

    #     docker
#    url: jdbc:mysql://mysql:3306/wiwy?serverTimezone=UTC&characterEncoding=UTF-8
#    username: wiwy
#    password: wiwy
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 70527473803-qkqq8iv6hrfbp7avmg1db4jndkatdlqn.apps.googleusercontent.com
            client-secret: dBkTWhqBIdbmoJxhr9e3qTl7
            scope:
              - email
              - profile
          facebook:
            client-id: 356017946093999
            client-secret: 61225fad078d6789d9b6c8e4c514731a
            scope:
              - email
              - public_profile
          naver:
            client-id: OTJUwQEDc03IuraKNDLY
            client-secret: XeyEeuey9M
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원 정보를 json으로 받는데 response라는 키 값으로 네이버가 리턴해줌.

logging:
  level:
    wiwy:
      covid: debug
    org.hibernate.SQL: debug
    #  org.hibernate.type: trace

